
spring:
  datasource:
  url: "jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE"
  username: sa
  password:
  driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
logging:
  level:
    root: INFO