spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/primitive4j-mongodb"
    username: postgres
    password: postgres
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        ddl-auto: create
logging:
  level:
    root: WARN
---
spring:
  config:
    activate:
      on-profile: "test"
  mvc:
    log-request-details: true
logging:
  level:
    root: info
    # sql: debug
    com:
      github:
        manosbatsis:
          domainprimitives: debug
    org:
      hibernate:
        orm:
          jdbc:
            # bind: trace
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: trace